#!/bin/sh
#
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

username=$$$whoami 

mkdir -p /tmp/$username/android-data/dalvik-cache
ANDROID_PRINTF_LOG=tag \
ANDROID_LOG_TAGS="" \
ANDROID_DATA=/tmp/$username/android-data \
ANDROID_ROOT=/scratch/$username/out/host/linux-x86 \
LD_LIBRARY_PATH=/scratch/$username/out/host/linux-x86/lib \
exec /scratch/$username/out/host/linux-x86/bin/dalvikvm -Xmx3200m -Xms3200m \
-Xbootclasspath\
:/scratch/$username/out/host/linux-x86/framework/core-hostdex.jar\
:/scratch/$username/out/host/linux-x86/framework/bouncycastle-hostdex.jar\
:/scratch/$username/out/host/linux-x86/framework/apache-xml-hostdex.jar \
$*

