/*
 * Stub for class sapphire.appexamples.jeffsdocs.app.Data
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.jeffsdocs.app.stubs;


public final class Data_Stub extends sapphire.appexamples.jeffsdocs.app.Data implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public Data_Stub (sapphire.appexamples.jeffsdocs.app.User $param_User_1, java.lang.String $param_String_2, sapphire.appexamples.jeffsdocs.app.Data.Permissions $param_Data$Permissions_3) {
        super($param_User_1, $param_String_2, $param_Data$Permissions_3);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public sapphire.policy.SapphirePolicy.SapphireClientPolicy $__getReference() {
        return $__client;
    }



    // Implementation of type()
    public java.lang.String type() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.type();
            else {
                Object[] $__params = null;
                String $__method = "public java.lang.String sapphire.appexamples.jeffsdocs.app.Data.type()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of setPermissions(User, Data.Permissions)
    public void setPermissions(sapphire.appexamples.jeffsdocs.app.User $param_User_1, sapphire.appexamples.jeffsdocs.app.Data.Permissions $param_Data$Permissions_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.setPermissions( $param_User_1,  $param_Data$Permissions_2);
            else {
                Object[] $__params = new Object[2];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.Data.setPermissions(sapphire.appexamples.jeffsdocs.app.User,sapphire.appexamples.jeffsdocs.app.Data$Permissions)";
                $__params[0] = $param_User_1;
                $__params[1] = $param_Data$Permissions_2;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of initialize(Data)
    public void initialize(sapphire.appexamples.jeffsdocs.app.Data $param_Data_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.initialize( $param_Data_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.Data.initialize(sapphire.appexamples.jeffsdocs.app.Data)";
                $__params[0] = $param_Data_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of hasAccess(User, Data.Permissions)
    public boolean hasAccess(sapphire.appexamples.jeffsdocs.app.User $param_User_1, sapphire.appexamples.jeffsdocs.app.Data.Permissions $param_Data$Permissions_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.hasAccess( $param_User_1,  $param_Data$Permissions_2);
            else {
                Object[] $__params = new Object[2];
                String $__method = "public boolean sapphire.appexamples.jeffsdocs.app.Data.hasAccess(sapphire.appexamples.jeffsdocs.app.User,sapphire.appexamples.jeffsdocs.app.Data$Permissions)";
                $__params[0] = $param_User_1;
                $__params[1] = $param_Data$Permissions_2;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of getLevel(User)
    public sapphire.appexamples.jeffsdocs.app.Data.Permissions getLevel(sapphire.appexamples.jeffsdocs.app.User $param_User_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getLevel( $param_User_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public sapphire.appexamples.jeffsdocs.app.Data$Permissions sapphire.appexamples.jeffsdocs.app.Data.getLevel(sapphire.appexamples.jeffsdocs.app.User)";
                $__params[0] = $param_User_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.jeffsdocs.app.Data.Permissions) $__result);
    }

    // Implementation of canShareData(User, User, Data.Permissions)
    public boolean canShareData(sapphire.appexamples.jeffsdocs.app.User $param_User_1, sapphire.appexamples.jeffsdocs.app.User $param_User_2, sapphire.appexamples.jeffsdocs.app.Data.Permissions $param_Data$Permissions_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.canShareData( $param_User_1,  $param_User_2,  $param_Data$Permissions_3);
            else {
                Object[] $__params = new Object[3];
                String $__method = "public boolean sapphire.appexamples.jeffsdocs.app.Data.canShareData(sapphire.appexamples.jeffsdocs.app.User,sapphire.appexamples.jeffsdocs.app.User,sapphire.appexamples.jeffsdocs.app.Data$Permissions)";
                $__params[0] = $param_User_1;
                $__params[1] = $param_User_2;
                $__params[2] = $param_Data$Permissions_3;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }
}
