/*
 * Stub for class sapphire.appexamples.jeffsdocs.app.UserManager
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.jeffsdocs.app.stubs;


public final class UserManager_Stub extends sapphire.appexamples.jeffsdocs.app.UserManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public UserManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public sapphire.policy.SapphirePolicy.SapphireClientPolicy $__getReference() {
        return $__client;
    }



    // Implementation of shareData(String, User, Data, Data.Permissions)
    public void shareData(java.lang.String $param_String_1, sapphire.appexamples.jeffsdocs.app.User $param_User_2, sapphire.appexamples.jeffsdocs.app.Data $param_Data_3, sapphire.appexamples.jeffsdocs.app.Data.Permissions $param_Data$Permissions_4) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.shareData( $param_String_1,  $param_User_2,  $param_Data_3,  $param_Data$Permissions_4);
            else {
                Object[] $__params = new Object[4];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.UserManager.shareData(java.lang.String,sapphire.appexamples.jeffsdocs.app.User,sapphire.appexamples.jeffsdocs.app.Data,sapphire.appexamples.jeffsdocs.app.Data$Permissions)";
                $__params[0] = $param_String_1;
                $__params[1] = $param_User_2;
                $__params[2] = $param_Data_3;
                $__params[3] = $param_Data$Permissions_4;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of login(String, String)
    public sapphire.appexamples.jeffsdocs.app.User login(java.lang.String $param_String_1, java.lang.String $param_String_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.login( $param_String_1,  $param_String_2);
            else {
                Object[] $__params = new Object[2];
                String $__method = "public sapphire.appexamples.jeffsdocs.app.User sapphire.appexamples.jeffsdocs.app.UserManager.login(java.lang.String,java.lang.String)";
                $__params[0] = $param_String_1;
                $__params[1] = $param_String_2;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.jeffsdocs.app.User) $__result);
    }

    // Implementation of dhtGetData()
    public java.util.Map dhtGetData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.dhtGetData();
            else {
                Object[] $__params = null;
                String $__method = "public java.util.Map<sapphire.policy.interfaces.dht.DHTKey, ?> sapphire.appexamples.jeffsdocs.app.UserManager.dhtGetData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Map) $__result);
    }

    // Implementation of createUser(String, String)
    public sapphire.appexamples.jeffsdocs.app.User createUser(java.lang.String $param_String_1, java.lang.String $param_String_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.createUser( $param_String_1,  $param_String_2);
            else {
                Object[] $__params = new Object[2];
                String $__method = "public sapphire.appexamples.jeffsdocs.app.User sapphire.appexamples.jeffsdocs.app.UserManager.createUser(java.lang.String,java.lang.String)";
                $__params[0] = $param_String_1;
                $__params[1] = $param_String_2;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.jeffsdocs.app.User) $__result);
    }
}
