/*
 * Stub for class sapphire.appexamples.jeffsdocs.app.User
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.jeffsdocs.app.stubs;


public final class User_Stub extends sapphire.appexamples.jeffsdocs.app.User implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public User_Stub (java.lang.String $param_String_1, java.lang.String $param_String_2) {
        super($param_String_1, $param_String_2);
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public sapphire.policy.SapphirePolicy.SapphireClientPolicy $__getReference() {
        return $__client;
    }



    // Implementation of toString()
    public java.lang.String toString() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.toString();
            else {
                Object[] $__params = null;
                String $__method = "public java.lang.String sapphire.appexamples.jeffsdocs.app.User.toString()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.String) $__result);
    }

    // Implementation of newSheet(String)
    public sapphire.appexamples.jeffsdocs.app.Sheet newSheet(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.newSheet( $param_String_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public sapphire.appexamples.jeffsdocs.app.Sheet sapphire.appexamples.jeffsdocs.app.User.newSheet(java.lang.String)";
                $__params[0] = $param_String_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.jeffsdocs.app.Sheet) $__result);
    }

    // Implementation of newDoc(String)
    public sapphire.appexamples.jeffsdocs.app.Doc newDoc(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.newDoc( $param_String_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public sapphire.appexamples.jeffsdocs.app.Doc sapphire.appexamples.jeffsdocs.app.User.newDoc(java.lang.String)";
                $__params[0] = $param_String_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.appexamples.jeffsdocs.app.Doc) $__result);
    }

    // Implementation of initialize(User)
    public void initialize(sapphire.appexamples.jeffsdocs.app.User $param_User_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.initialize( $param_User_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.User.initialize(sapphire.appexamples.jeffsdocs.app.User)";
                $__params[0] = $param_User_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of getOfferedData()
    public java.util.Set getOfferedData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getOfferedData();
            else {
                Object[] $__params = null;
                String $__method = "public java.util.Set<sapphire.appexamples.jeffsdocs.app.Data> sapphire.appexamples.jeffsdocs.app.User.getOfferedData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Set) $__result);
    }

    // Implementation of getData()
    public java.util.Set getData() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getData();
            else {
                Object[] $__params = null;
                String $__method = "public java.util.Set<sapphire.appexamples.jeffsdocs.app.Data> sapphire.appexamples.jeffsdocs.app.User.getData()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.Set) $__result);
    }

    // Implementation of deleteData(Data)
    public void deleteData(sapphire.appexamples.jeffsdocs.app.Data $param_Data_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.deleteData( $param_Data_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.User.deleteData(sapphire.appexamples.jeffsdocs.app.Data)";
                $__params[0] = $param_Data_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of checkPassword(String)
    public boolean checkPassword(java.lang.String $param_String_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.checkPassword( $param_String_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public boolean sapphire.appexamples.jeffsdocs.app.User.checkPassword(java.lang.String)";
                $__params[0] = $param_String_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }

    // Implementation of addData(Data)
    public void addData(sapphire.appexamples.jeffsdocs.app.Data $param_Data_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.addData( $param_Data_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.User.addData(sapphire.appexamples.jeffsdocs.app.Data)";
                $__params[0] = $param_Data_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of acceptData(Data)
    public void acceptData(sapphire.appexamples.jeffsdocs.app.Data $param_Data_1) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.acceptData( $param_Data_1);
            else {
                Object[] $__params = new Object[1];
                String $__method = "public void sapphire.appexamples.jeffsdocs.app.User.acceptData(sapphire.appexamples.jeffsdocs.app.Data)";
                $__params[0] = $param_Data_1;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
