/*
 * Stub for class sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.policy.stubs;


public final class LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_Stub extends sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy implements sapphire.kernel.common.KernelObjectStub {

    private static final long serialVersionUID = 2L;
    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;

    public LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public Object $__makeKernelRPC(java.lang.String method, Object[] params) throws java.rmi.RemoteException, java.lang.Exception {
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, $__oid, method, params);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) { 
        LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_Stub other = (LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() { 
        return $__oid.getID();
    }


    // Implementation of updateReplicas(byte[])
    public void updateReplicas(byte[] $param_arrayOf_byte_1) {
        String $__method = "public synchronized void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.updateReplicas(byte[])";
        Object[] $__params = new Object[1];
        $__params[0] = $param_arrayOf_byte_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of update(byte[])
    public void update(byte[] $param_arrayOf_byte_1) {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.update(byte[])";
        Object[] $__params = new Object[1];
        $__params[0] = $param_arrayOf_byte_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setMasterServer(LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy)
    public void setMasterServer(sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy $param_LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_1) {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.setMasterServer(sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setAsMaster()
    public void setAsMaster() {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.setAsMaster()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of replicate()
    public sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy replicate() {
        String $__method = "public sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.replicate()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy) $__result);
    }

    // Implementation of pin(InetSocketAddress)
    public void pin(java.net.InetSocketAddress $param_InetSocketAddress_1) {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.pin(java.net.InetSocketAddress)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_InetSocketAddress_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onRPC(String, Object[])
    public java.lang.Object onRPC(java.lang.String $param_String_1, java.lang.Object[] $param_arrayOf_Object_2)
            throws java.lang.Exception {
        String $__method = "public synchronized java.lang.Object sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.onRPC(java.lang.String,java.lang.Object[]) throws java.lang.Exception";
        Object[] $__params = new Object[2];
        $__params[0] = $param_String_1;
        $__params[1] = $param_arrayOf_Object_2;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of onMembershipChange()
    public void onMembershipChange() {
        String $__method = "public void sapphire.policy.DefaultSapphirePolicy$DefaultServerPolicy.onMembershipChange()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onHighLatency()
    public void onHighLatency() {
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.onHighLatency()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireGroupPolicy)
    public void onCreate(sapphire.policy.SapphirePolicy.SapphireGroupPolicy $param_SapphirePolicy$SapphireGroupPolicy_1) {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireGroupPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_SapphirePolicy$SapphireGroupPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of objectToByteArray()
    public byte[] objectToByteArray() {
        String $__method = "public byte[] sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.objectToByteArray()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((byte[]) $__result);
    }

    // Implementation of load()
    public double load() {
        String $__method = "public double sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.load()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Double) $__result).doubleValue();
    }

    // Implementation of getGroup()
    public sapphire.policy.SapphirePolicy.SapphireGroupPolicy getGroup() {
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireGroupPolicy sapphire.policy.DefaultSapphirePolicy$DefaultServerPolicy.getGroup()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireGroupPolicy) $__result);
    }

    // Implementation of byteArrayToObject(byte[])
    public java.lang.Object byteArrayToObject(byte[] $param_arrayOf_byte_1) {
        String $__method = "public java.lang.Object sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.byteArrayToObject(byte[])";
        Object[] $__params = new Object[1];
        $__params[0] = $param_arrayOf_byte_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of addReplica(LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy)
    public void addReplica(sapphire.policy.scalability.LoadBalancedMasterSlave.LoadBalancedMasterSlaveServerPolicy $param_LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_1) {
        String $__method = "public void sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy.addReplica(sapphire.policy.scalability.LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_LoadBalancedMasterSlave$LoadBalancedMasterSlaveServerPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
