/*
 * Stub for class sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.policy.stubs;


public final class MasterSlavePolicy$MasterSlaveServerPolicy_Stub extends sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy implements sapphire.kernel.common.KernelObjectStub {

    private static final long serialVersionUID = 2L;
    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;

    public MasterSlavePolicy$MasterSlaveServerPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public Object $__makeKernelRPC(java.lang.String method, Object[] params) throws java.rmi.RemoteException, java.lang.Exception {
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, $__oid, method, params);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) { 
        MasterSlavePolicy$MasterSlaveServerPolicy_Stub other = (MasterSlavePolicy$MasterSlaveServerPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() { 
        return $__oid.getID();
    }


    // Implementation of update(byte[])
    public void update(byte[] $param_arrayOf_byte_1) {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.update(byte[])";
        Object[] $__params = new Object[1];
        $__params[0] = $param_arrayOf_byte_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setMasterServer(MasterSlavePolicy.MasterSlaveServerPolicy)
    public void setMasterServer(sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy $param_MasterSlavePolicy$MasterSlaveServerPolicy_1) {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.setMasterServer(sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_MasterSlavePolicy$MasterSlaveServerPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of setAsMaster()
    public void setAsMaster() {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.setAsMaster()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of replicate()
    public sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy replicate() {
        String $__method = "public sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.replicate()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy) $__result);
    }

    // Implementation of onRPC(String, Object[])
    public java.lang.Object onRPC(java.lang.String $param_String_1, java.lang.Object[] $param_arrayOf_Object_2)
            throws java.lang.Exception {
        String $__method = "public synchronized java.lang.Object sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.onRPC(java.lang.String,java.lang.Object[]) throws java.lang.Exception";
        Object[] $__params = new Object[2];
        $__params[0] = $param_String_1;
        $__params[1] = $param_arrayOf_Object_2;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of onMembershipChange()
    public void onMembershipChange() {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.onMembershipChange()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onHighLatency()
    public void onHighLatency() {
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.onHighLatency()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireGroupPolicy)
    public void onCreate(sapphire.policy.SapphirePolicy.SapphireGroupPolicy $param_SapphirePolicy$SapphireGroupPolicy_1) {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireGroupPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_SapphirePolicy$SapphireGroupPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of objectToByteArray()
    public byte[] objectToByteArray() {
        String $__method = "public byte[] sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.objectToByteArray()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((byte[]) $__result);
    }

    // Implementation of getGroup()
    public sapphire.policy.SapphirePolicy.SapphireGroupPolicy getGroup() {
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireGroupPolicy sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.getGroup()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireGroupPolicy) $__result);
    }

    // Implementation of getAppObject()
    public sapphire.common.AppObject getAppObject() {
        String $__method = "public sapphire.common.AppObject sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.getAppObject()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.common.AppObject) $__result);
    }

    // Implementation of byteArrayToObject(byte[])
    public java.lang.Object byteArrayToObject(byte[] $param_arrayOf_byte_1) {
        String $__method = "public java.lang.Object sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.byteArrayToObject(byte[])";
        Object[] $__params = new Object[1];
        $__params[0] = $param_arrayOf_byte_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of addReplica(MasterSlavePolicy.MasterSlaveServerPolicy)
    public void addReplica(sapphire.policy.replicate.MasterSlavePolicy.MasterSlaveServerPolicy $param_MasterSlavePolicy$MasterSlaveServerPolicy_1) {
        String $__method = "public void sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy.addReplica(sapphire.policy.replicate.MasterSlavePolicy$MasterSlaveServerPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_MasterSlavePolicy$MasterSlaveServerPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
