/*
 * Stub for class sapphire.policy.replicate.PaxosReplicatePolicy.PaxosReplicateServerPolicy
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.policy.stubs;


public final class PaxosReplicatePolicy$PaxosReplicateServerPolicy_Stub extends sapphire.policy.replicate.PaxosReplicatePolicy.PaxosReplicateServerPolicy implements sapphire.kernel.common.KernelObjectStub {

    private static final long serialVersionUID = 2L;
    sapphire.kernel.common.KernelOID $__oid = null;
    java.net.InetSocketAddress $__hostname = null;

    public PaxosReplicatePolicy$PaxosReplicateServerPolicy_Stub(sapphire.kernel.common.KernelOID oid) {
        this.$__oid = oid;
    }

    public sapphire.kernel.common.KernelOID $__getKernelOID() {
        return this.$__oid;
    }

    public java.net.InetSocketAddress $__getHostname() {
        return this.$__hostname;
    }

    public void $__updateHostname(java.net.InetSocketAddress hostname) {
        this.$__hostname = hostname;
    }

    public Object $__makeKernelRPC(java.lang.String method, Object[] params) throws java.rmi.RemoteException, java.lang.Exception {
        try {
            return sapphire.kernel.common.GlobalKernelReferences.nodeServer.getKernelClient().makeKernelRPC(this, $__oid, method, params);
        } catch (sapphire.kernel.common.KernelObjectNotFoundException e) {
            throw new java.rmi.RemoteException();
        }
    }

    @Override
    public boolean equals(Object obj) { 
        PaxosReplicatePolicy$PaxosReplicateServerPolicy_Stub other = (PaxosReplicatePolicy$PaxosReplicateServerPolicy_Stub) obj;
        if (! other.$__oid.equals($__oid))
            return false;
        return true;
    }
    @Override
    public int hashCode() { 
        return $__oid.getID();
    }


    // Implementation of startServers()
    public java.util.List startServers() {
        String $__method = "public java.util.List<sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy> sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.startServers()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of setServers(List, int)
    public void setServers(java.util.List $param_List_1, int $param_int_2) {
        String $__method = "public void sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.setServers(java.util.List<sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy>,int)";
        Object[] $__params = new Object[2];
        $__params[0] = $param_List_1;
        $__params[1] = $param_int_2;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of prepare(int, int, int)
    public sapphire.policy.replicate.PaxosReplicatePolicy.RoundState prepare(int $param_int_1, int $param_int_2, int $param_int_3) {
        String $__method = "public sapphire.policy.replicate.PaxosReplicatePolicy$RoundState sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.prepare(int,int,int)";
        Object[] $__params = new Object[3];
        $__params[0] = $param_int_1;
        $__params[1] = $param_int_2;
        $__params[2] = $param_int_3;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.replicate.PaxosReplicatePolicy.RoundState) $__result);
    }

    // Implementation of paxosReplicatePin(String)
    public void paxosReplicatePin(java.lang.String $param_String_1)
            throws java.rmi.RemoteException {
        String $__method = "public void sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.paxosReplicatePin(java.lang.String) throws java.rmi.RemoteException";
        Object[] $__params = new Object[1];
        $__params[0] = $param_String_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of paxosReplicate()
    public sapphire.policy.replicate.PaxosReplicatePolicy.PaxosReplicateServerPolicy paxosReplicate() {
        String $__method = "public sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.paxosReplicate()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.replicate.PaxosReplicatePolicy.PaxosReplicateServerPolicy) $__result);
    }

    // Implementation of onRPC(String, Object[])
    public java.lang.Object onRPC(java.lang.String $param_String_1, java.lang.Object[] $param_arrayOf_Object_2)
            throws java.lang.Exception {
        String $__method = "public synchronized java.lang.Object sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.onRPC(java.lang.String,java.lang.Object[]) throws java.lang.Exception";
        Object[] $__params = new Object[2];
        $__params[0] = $param_String_1;
        $__params[1] = $param_arrayOf_Object_2;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return $__result;
    }

    // Implementation of onMembershipChange()
    public void onMembershipChange() {
        String $__method = "public void sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.onMembershipChange()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onHighLatency()
    public void onHighLatency() {
        String $__method = "public void sapphire.policy.DefaultSapphirePolicyUpcallImpl$DefaultSapphireServerPolicyUpcallImpl.onHighLatency()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of onCreate(SapphirePolicy.SapphireGroupPolicy)
    public void onCreate(sapphire.policy.SapphirePolicy.SapphireGroupPolicy $param_SapphirePolicy$SapphireGroupPolicy_1) {
        String $__method = "public void sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.onCreate(sapphire.policy.SapphirePolicy$SapphireGroupPolicy)";
        Object[] $__params = new Object[1];
        $__params[0] = $param_SapphirePolicy$SapphireGroupPolicy_1;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of learn(int, PaxosReplicatePolicy.RPC, Boolean, PaxosReplicatePolicy.State)
    public sapphire.policy.replicate.PaxosReplicatePolicy.Tuple learn(int $param_int_1, sapphire.policy.replicate.PaxosReplicatePolicy.RPC $param_PaxosReplicatePolicy$RPC_2, java.lang.Boolean $param_Boolean_3, sapphire.policy.replicate.PaxosReplicatePolicy.State $param_PaxosReplicatePolicy$State_4)
            throws java.lang.Exception {
        String $__method = "public sapphire.policy.replicate.PaxosReplicatePolicy$Tuple sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.learn(int,sapphire.policy.replicate.PaxosReplicatePolicy$RPC,java.lang.Boolean,sapphire.policy.replicate.PaxosReplicatePolicy$State) throws java.lang.Exception";
        Object[] $__params = new Object[4];
        $__params[0] = $param_int_1;
        $__params[1] = $param_PaxosReplicatePolicy$RPC_2;
        $__params[2] = $param_Boolean_3;
        $__params[3] = $param_PaxosReplicatePolicy$State_4;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.replicate.PaxosReplicatePolicy.Tuple) $__result);
    }

    // Implementation of getGroup()
    public sapphire.policy.SapphirePolicy.SapphireGroupPolicy getGroup() {
        String $__method = "public sapphire.policy.SapphirePolicy$SapphireGroupPolicy sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.getGroup()";
        Object[] $__params = null;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((sapphire.policy.SapphirePolicy.SapphireGroupPolicy) $__result);
    }

    // Implementation of accept(int, int, PaxosReplicatePolicy.Proposal)
    public boolean accept(int $param_int_1, int $param_int_2, sapphire.policy.replicate.PaxosReplicatePolicy.Proposal $param_PaxosReplicatePolicy$Proposal_3) {
        String $__method = "public boolean sapphire.policy.replicate.PaxosReplicatePolicy$PaxosReplicateServerPolicy.accept(int,int,sapphire.policy.replicate.PaxosReplicatePolicy$Proposal)";
        Object[] $__params = new Object[3];
        $__params[0] = $param_int_1;
        $__params[1] = $param_int_2;
        $__params[2] = $param_PaxosReplicatePolicy$Proposal_3;
        java.lang.Object $__result = null;
        try {
            $__result = $__makeKernelRPC($__method, $__params);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.lang.Boolean) $__result).booleanValue();
    }
}
