/*
 * Stub for class sapphire.appexamples.minnietwitter.app.TagManager
 * Generated by Sapphire Compiler (sc).
 */
package sapphire.appexamples.minnietwitter.app.stubs;


public final class TagManager_Stub extends sapphire.appexamples.minnietwitter.app.TagManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public TagManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public sapphire.policy.SapphirePolicy.SapphireClientPolicy $__getReference() {
        return $__client;
    }



    // Implementation of getTweetsForTag(String, BigInteger, BigInteger)
    public java.util.List getTweetsForTag(java.lang.String $param_String_1, java.math.BigInteger $param_BigInteger_2, java.math.BigInteger $param_BigInteger_3) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getTweetsForTag( $param_String_1,  $param_BigInteger_2,  $param_BigInteger_3);
            else {
                Object[] $__params = new Object[3];
                String $__method = "public java.util.List<sapphire.appexamples.minnietwitter.app.Tweet> sapphire.appexamples.minnietwitter.app.TagManager.getTweetsForTag(java.lang.String,java.math.BigInteger,java.math.BigInteger)";
                $__params[0] = $param_String_1;
                $__params[1] = $param_BigInteger_2;
                $__params[2] = $param_BigInteger_3;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((java.util.List) $__result);
    }

    // Implementation of addTag(String, Tweet)
    public void addTag(java.lang.String $param_String_1, sapphire.appexamples.minnietwitter.app.Tweet $param_Tweet_2) {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.addTag( $param_String_1,  $param_Tweet_2);
            else {
                Object[] $__params = new Object[2];
                String $__method = "public void sapphire.appexamples.minnietwitter.app.TagManager.addTag(java.lang.String,sapphire.appexamples.minnietwitter.app.Tweet)";
                $__params[0] = $param_String_1;
                $__params[1] = $param_Tweet_2;
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
